#
# Module manifest for module 'posh-winget'
#
# Generated by: nuits.jp
#
# Generated on: 2021/10/29
#

@{
    RootModule = 'posh-winget.psm1'
    ModuleVersion = '0.0.2'
    GUID = '9b311919-2cd3-4c9f-bf8f-b35cf063da58'
    Author = 'nuits.jp'
    Copyright = '(c) nuits.jp. All rights reserved.'
    PowerShellVersion = '3.0'
    Description = 'Support PowerShell module for winget.'
    FunctionsToExport = @(
        'Install-Winget'
        'Test-InstalledWinget'
    )
    CmdletsToExport = @()
    VariablesToExport = '*'
    AliasesToExport = @()

    PrivateData = @{

        PSData = @{
            ProjectUri = 'https://github.com/nuitsjp/posh-winget'
            LicenseUri = 'https://raw.githubusercontent.com/nuitsjp/posh-winget/main/LICENSE'
            ReleaseNotes = 'https://github.com/nuitsjp/posh-winget/releases'
            Tags = @('winget')

            # Tags applied to this module. These help with module discovery in online galleries.
            # 

            # A URL to the license for this module.

            # A URL to the main website for this project.

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # 

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}

